In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


## TASK 1

In [9]:
from sklearn.datasets import make_regression
X, y = make_regression(n_samples=100, n_features=20, noise=10, random_state=42)
y

array([ 112.70233835, -251.31800244,    9.96476522,  133.93931697,
          4.2581094 ,   -5.31253045,  -64.04713907, -310.25999142,
         31.98763282,   11.01090825, -246.95406877,  -93.30912453,
       -100.90507735,   54.64259849,  -33.79282037,   86.30465566,
         89.70110819, -209.87555665,   50.72379345,  420.25825187,
        134.63627558,   93.93691957,  -34.38193529,  225.87509498,
        353.0086491 , -275.20266926,  252.88541717, -362.16087086,
        366.24565465, -243.25938612,   94.14377093,  -49.32834032,
         60.00057562,  215.42511865,  273.80501286,  274.04022805,
        315.74644977,   31.78317575,  -26.66604594,  243.307989  ,
       -238.17026837,  283.66533576,  -52.18949103,  -90.25662114,
        -66.9239505 ,   37.94500785,  143.26393459,  235.77390487,
        -22.0852962 ,   94.13371344,  -63.38850036,  -36.69795809,
         57.38953777, -167.76626889,   97.12667422,   41.03082142,
        113.36238546, -329.82311   ,  232.87332169, -107.93371

In [10]:
features = pd.DataFrame(data=X)

In [11]:
features.describe()

0           1           2           3           4           5   \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean     0.066483   -0.090669    0.148793   -0.009252    0.066883    0.138678   
std      1.029991    0.977525    0.933608    0.895542    0.927696    0.923655   
min     -2.896255   -1.975467   -2.499406   -2.172670   -2.423879   -1.703382   
25%     -0.534866   -0.857052   -0.356271   -0.640109   -0.496090   -0.552580   
50%     -0.028445   -0.076344    0.178798   -0.016458    0.131194    0.145691   
75%      0.757704    0.531959    0.721849    0.564199    0.493497    0.839220   
max      2.290943    2.439752    2.526932    2.122156    3.137749    3.078881   

               6           7           8           9           10          11  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean    -0.020263    0.135566    0.048246    0.021527   -0.067366    0.116212   
std      0.978568    0.946059    0.904497    1.078934    0.849485    1.024664   
min     -1.748532   -1.760809   -2.471645   -3.241267   -2.703232   -2.198806   
25%     -0.766607   -0.655722   -0.585946   -0.650129   -0.555773   -0.659615   
50%     -0.020941    0.147305   -0.012252    0.044188   -0.010110    0.214404   
75%      0.622830    0.759989    0.654505    0.691722    0.466162    0.819755   
max      2.270693    2.455300    2.133033    2.560085    1.848956    2.601683   

               12          13          14          15          16          17  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean     0.181512   -0.021257    0.140830    0.164645   -0.083936    0.011392   
std      1.045479    1.053048    0.921654    1.088579    1.063061    1.186164   
min     -2.619745   -2.591042   -2.872262   -2.152891   -2.696887   -2.940389   
25%     -0.531525   -0.676945   -0.435979   -0.608664   -0.945732   -0.684015   
50%      0.046091   -0.094711    0.174999    0.024079   -0.004435    0.091795   
75%      0.997346    0.648388    0.751524    0.860472    0.623706    0.821707   
max      2.644343    3.193108    2.720169    3.852731    2.170943    2.558199   

               18          19  
count  100.000000  100.000000  
mean    -0.013781   -0.032560  
std      1.007022    0.885011  
min     -2.151815   -2.650970  
25%     -0.775432   -0.554979  
50%     -0.022596    0.040263  
75%      0.584392    0.591680  
max      2.403416    1.765454

In [12]:
lables = pd.DataFrame(data=y)

In [13]:
lables.describe()

0
count  100.000000
mean    17.163369
std    170.584475
min   -457.487496
25%    -65.175543
50%      7.849974
75%    115.345338
max    420.258252

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler

# Создаем данные
X, y, coefs = make_regression(n_samples=1000, n_features=200, noise=10, random_state=42, coef=True)

# Выбираем случайные 100 наблюдений
X_sampled, _, y_sampled, _ = train_test_split(X, y, test_size=0.9, random_state=42)

# Строим модели
linear_reg = LinearRegression()
ridge_reg = Ridge(random_state=1)
lasso_reg = Lasso()

# Обучаем модели на случайных 100 наблюдениях
linear_reg.fit(X_sampled, y_sampled)
ridge_reg.fit(X_sampled, y_sampled)
lasso_reg.fit(X_sampled, y_sampled)

# Получаем предсказания
y_pred_linear = linear_reg.predict(X)
y_pred_ridge = ridge_reg.predict(X)
y_pred_lasso = lasso_reg.predict(X)

# Оцениваем качество по mean_squared_error
mse_linear = mean_squared_error(y, y_pred_linear)
mse_ridge = mean_squared_error(y, y_pred_ridge)
mse_lasso = mean_squared_error(y, y_pred_lasso)

print("MSE Linear Regression:", mse_linear)
print("MSE Ridge Regression:", mse_ridge)
print("MSE Lasso Regression:", mse_lasso)


MSE Linear Regression: 18941.481963743186
MSE Ridge Regression: 18892.002554314295
MSE Lasso Regression: 132.02186450737


In [15]:
# Истинные значения коэффициентов
true_coefs = coefs

# Оцениваем близость коэффициентов
coef_similarity_linear = np.abs(linear_reg.coef_ - true_coefs).mean()
coef_similarity_ridge = np.abs(ridge_reg.coef_ - true_coefs).mean()
coef_similarity_lasso = np.abs(lasso_reg.coef_ - true_coefs).mean()

print("Mean Coefficient Similarity Linear Regression:", coef_similarity_linear)
print("Mean Coefficient Similarity Ridge Regression:", coef_similarity_ridge)
print("Mean Coefficient Similarity Lasso Regression:", coef_similarity_lasso)

Mean Coefficient Similarity Linear Regression: 6.692230417837655
Mean Coefficient Similarity Ridge Regression: 6.649737949291521
Mean Coefficient Similarity Lasso Regression: 0.170953102766091


In [16]:
X, y, coefs = make_regression(n_samples=100, n_features=20, noise=10, random_state=42, coef=True)
X

array([[-0.92216532,  1.87679581,  0.75698862, ..., -0.05558467,
         0.10939479, -1.77872025],
       [-0.08310557, -1.4575515 , -1.40631746, ...,  0.11502608,
        -0.31905394,  0.31917451],
       [ 0.81080827, -1.66249199, -0.13430874, ..., -0.21492103,
        -0.56216803, -1.09096643],
       ...,
       [-0.15246984, -1.33123295,  0.1335409 , ...,  2.49299952,
         0.91907648, -1.10336661],
       [-1.37961816,  0.51308542, -0.97165673, ...,  0.75429133,
        -0.02652126, -0.6414816 ],
       [-2.84854262, -1.11966989,  0.77169871, ...,  0.47704083,
        -1.5565819 , -0.4677012 ]])

In [17]:
X[20]

array([ 1.7722516 ,  0.46877426, -0.02751491, -0.87798259, -0.80317895,
        1.49268857, -0.45709626,  0.3017919 , -0.60221206,  1.66125921,
       -0.10015408, -0.82688035, -0.22647889,  0.36736551, -0.2711236 ,
        1.22693322, -0.99838544, -0.20367375,  0.91358463,  0.76608028])

In [28]:
X, y, coefs = make_regression(n_samples=100, n_features=20, noise=10, random_state=42, coef=True)
X = pd.DataFrame(data=X, columns = [f'x{i}' for i in range(20)])

# Добавляем столбец x['x20'] равный x['x1']
X['x19'] = X['x1']

# Нормируем данные
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [29]:
linear_reg = LinearRegression()
ridge_reg = Ridge(random_state=1)
lasso_reg = Lasso()
linear_reg.fit(X_scaled, y)
ridge_reg.fit(X_scaled, y)
lasso_reg.fit(X_scaled, y)

Lasso()

In [30]:
coef_change_linear = np.abs(linear_reg.coef_ - coefs).mean() > 0.1
coef_change_ridge = np.abs(ridge_reg.coef_ - coefs).mean() > 0.1
coef_change_lasso = np.abs(lasso_reg.coef_ - coefs).mean() > 0.1

# Зануление коэффициентов Lasso
zero_coefs_lasso = (lasso_reg.coef_ == 0).any()

In [31]:
# coef_reduction_ridge = (np.abs(ridge_reg.coef_[X.columns == 'x1']) < np.abs(coefs[X.columns == 'x1']) / 2) & (np.abs(ridge_reg.coef_[X.columns == 'x19']) < np.abs(coefs[X.columns == 'x19']) / 2)
# coef_reduction_linear = (np.abs(linear_reg.coef_[X.columns == 'x1']) < np.abs(coefs[X.columns == 'x1']) / 2) & (np.abs(linear_reg.coef_[X.columns == 'x19']) < np.abs(coefs[X.columns == 'x19']) / 2)

In [32]:
# Убираем из X важный x['x1']
X, y, coefs = make_regression(n_samples=100, n_features=20, noise=10, random_state=42, coef=True)
X = pd.DataFrame(data=X, columns = [f'x{i}' for i in range(20)])
X_without_x1 = X.drop(columns=['x1'])

In [33]:
scaler = StandardScaler()
X_without_x1_scaled = scaler.fit_transform(X_without_x1)
linear_reg_without_x1 = LinearRegression()
ridge_reg_without_x1 = Ridge(random_state=1)
lasso_reg_without_x1 = Lasso()
linear_reg_without_x1.fit(X_without_x1_scaled, y)
ridge_reg_without_x1.fit(X_without_x1_scaled, y)
lasso_reg_without_x1.fit(X_without_x1_scaled, y)


Lasso()

In [34]:

coef_change_linear_without_x1 = np.abs(linear_reg_without_x1.coef_ - coefs[1:]).mean() > 0.1
coef_change_ridge_without_x1 = np.abs(ridge_reg_without_x1.coef_ - coefs[1:]).mean() > 0.1
coef_change_lasso_without_x1 = np.abs(lasso_reg_without_x1.coef_ - coefs[1:]).mean() > 0.1
zero_coefs_lasso_without_x1 = (lasso_reg_without_x1.coef_ == 0).any()

# coef_reduction_ridge_without_x1 = (np.abs(ridge_reg_without_x1.coef_) < np.abs(coefs[1:]) / 2)
# coef_reduction_linear_without_x1 = (np.abs(linear_reg_without_x1.coef_) < np.abs(coefs[1:]) / 2)